# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
        exclude: LICENSE
      - id: end-of-file-fixer
        exclude: LICENSE
      - id: check-yaml
        exclude: ^charts/.*?/templates/|^.gitlab-ci.yml
        args: [-m]
      - id: check-added-large-files
        exclude: ^examples/.*\.mp4$
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: requirements-txt-fixer

  - repo: https://github.com/psf/black
    rev: "23.3.0"
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: "5.12.0"
    hooks:
      - id: isort
        args: ["--resolve-all-configs"]

  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.3"
    hooks:
      - id: poetry-check
        args: ["-C", "./src/lymphocyte", "--lock"]
      - id: poetry-lock
        args: ["-C", "./src/lymphocyte", "--no-update"]
      - id: poetry-install
        args: ["-C", "./src/lymphocyte"]

  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint
