apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: hddp
  name: hddp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hddp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        app: hddp
        name: hddp
        id: hddp
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: ci.tno.nl/self-healing/host/hddp:master
        imagePullPolicy: ""
        name: hddp
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
