apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 9000
      targetPort: 9000
