apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: php
  name: php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        app: php
        name: php-deployment
        id: php
    spec:
      containers:
        - image: ci.tno.nl/self-healing/web-application/vulnerable-php-container:master
          imagePullPolicy: ""
          name: php-deployment
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: { }
