apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 6379
      targetPort: 6379
