---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testapp2-alertmanager-config
data:
  alertmanager.yml: |-
    route:
      receiver: some_receiver
      group_wait: 1s
      group_interval: 5s
      repeat_interval: 60s
    receivers:
      - name: some_receiver
        webhook_configs:
          - url: http://127.0.0.1:12345/alertmanager_webhook
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testapp2-lymphocyte-config
data:
  settings.yaml: |-
    triggers:
      - kind: threat_level
        name: threat_level_other_changed
        identifier: other
      - kind: threat_level
        name: threat_level_self_changed
        identifier: self
    actions:
      - kind: debug
        name: debug_all_threat_levels
        message: |
          All threat levels:
          {{ other_threat_levels_manager.get() | join("\n") }}
          Max: {{ other_threat_levels_manager.get() | max(attribute="level") }}

      - kind: increment_threat_level
        name: increment_threat_level
        for_seconds: 30

      - kind: send_rest_request
        name: enable_rate_limiter
        url: http://localhost:8000/enable_rate_limiter
      - kind: send_rest_request
        name: disable_rate_limiter
        url: http://localhost:8000/disable_rate_limiter

    rules:
      - kind: conditional
        triggers:
          - threat_level_other_changed
        actions:
          - increment_threat_level

      - kind: conditional
        triggers:
          - threat_level_other_changed
        condition: >
          (other_threat_levels_manager.get(identifier_match="other") | map(attribute=2) | max) >= 1
        actions:
          - enable_rate_limiter
      - kind: conditional
        triggers:
          - threat_level_other_changed
        condition: >
          (other_threat_levels_manager.get(identifier_match="other") | map(attribute=2) | max) < 1
        actions:
          - disable_rate_limiter
    neighbors:
      - identifier: other
        threat_level_websocket_url: ws://test-app-headless:12345/threat_level

    ttl_manager:
      base_ttl_seconds: 86400

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: testapp2-prometheus-config
data:
  alerts.yml: |-
    groups:
    - name: example
      interval: 1s
      rules:
        - alert: High CPU usage
          expr: rate(process_cpu_seconds_total{job="testapp"}[20s]) > 0.9
        - alert: Any failed logins
          expr: rate(http_requests_total{job="testapp",handler="/token",status!="2xx"}[10s]) > 0
        - alert: Server errors
          expr: rate(http_requests_total{job="testapp",status="5xx"}[10s]) > 0
        - alert: Download file errors
          expr: rate(http_requests_total{job="testapp",handler="/download_file",status!="2xx"}[10s]) > 0

  prometheus.yml: |-
    global:
      # How frequently to scrape targets by default.
      scrape_interval: 1s
      scrape_timeout: 1s
    rule_files:
      - /etc/prometheus/alerts.yml
    scrape_configs:
      - job_name: testapp
        static_configs:
          - targets:
              - "127.0.0.1:8000"
      - job_name: lymphocyte
        static_configs:
          - targets:
              - "127.0.0.1:12345"
    alerting:
      alertmanagers:
        - scheme: http
          static_configs:
            - targets:
                - "127.0.0.1:9093"
