apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-app
  labels:
    app: test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
        # sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: python-lymphocyte
          image: "ci.tno.nl:4567/tri/self-healing/sh4cs2-testbed/lymphocyte:development"
          ports:
            - containerPort: 12345
              name: lymphocyte-http
          env:
            - name: LYMPHOCYTE_CONFIG
              value: /lymphocyte/settings.yaml
          volumeMounts:
            - name: lymphocyte-config
              mountPath: /lymphocyte
        - name: prometheus
          image: prom/prometheus
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus
          ports:
            - containerPort: 9090
              name: prometheus
        - name: alertmanager
          image: prom/alertmanager
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager
          ports:
            - containerPort: 9093
              name: alertmanager
        - name: test-app
          image: "ci.tno.nl:4567/tri/self-healing/sh4cs2-testbed/testapp:development"
          env:
            - name: BASE_URL
              value: "http://test-app2"
          ports:
            - containerPort: 8000
              name: http
          volumeMounts:
            - name: app-logs
              mountPath: /logs
          livenessProbe:
            httpGet:
              path: /livenessProbe
              port: 12345
            periodSeconds: 1
          startupProbe:
            httpGet:
              path: /startupProbe
              port: 12345
            periodSeconds: 1
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /readinessProbe
              port: 12345
            periodSeconds: 1
      volumes:
        - name: prometheus-config
          configMap:
            name: testapp-prometheus-config
        - name: alertmanager-config
          configMap:
            name: testapp-alertmanager-config
        - name: lymphocyte-config
          configMap:
            name: testapp-lymphocyte-config
        - name: app-logs
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: "lymphocyte"
    port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    app: test-app
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-app
  name: test-app-headless
spec:
  ports:
  - name: "http"
    port: 80
    protocol: TCP
    targetPort: 8000
  - name: "lymphocyte"
    port: 12345
    protocol: TCP
    targetPort: 12345
  selector:
    app: test-app
  clusterIP: None
