apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        app: mongo
        name: mongo
        id: mongo
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - image: ci.tno.nl/self-healing/host/mongo:master
        imagePullPolicy: ""
        name: mongo
        resources: {}
        env:
          - name: MONGO_INITDB_DATABASE
            value: "detectors"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
